server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 30m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: spring
    password: 1234

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 5MB
      max-request-size: 15MB

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath*:/mapper/*.xml
#  type-aliases-package: com.app.threetier.domain; com.app.threetier.dto;
#  type-handlers-package: com.app.threetier.mybatis.handler
